### PR TITLE
Added online lua formatter link

### PR DESCRIPTION
**Pull request by rahulkumarsingh73690**
I suggest you add this Lua formatter because many users want to format shortcode quickly

### CODE REVIEW

**Comment by rahulkumarsingh73690** [comment]
Review this pr @Koihik

**Comment by Koihik** [comment]
This online tools seem implemented with other libraries.

**Comment by rahulkumarsingh73690** [comment]
> This online tools seem implemented with other libraries.

Yes, I know but this helps users who want to format a small line of Lua code. As a user perspective for 10 lines of code formatting no one installs formatted in cli 

Now it depends on you if you like my suggestion then merge this PR

**Comment by Koihik** [comment]
Generally, try online means you can try *this library* online. And users can easily install Luaformatter plug-ins in the IDE. So I will close this PR and thanks for your advice.

**Pull request closed without merging**
