### PR TITLE
Allow to be built with g++ version less than 8 on Linux

### PR DESCRIPTION
**Pull request by spacewander**

### CODE REVIEW

**Comment by karanankit01** [comment]
Since <experimental/filesystem> is not stable, so user is recommended to update their compiler.

**Comment by spacewander** [comment]
@karanankit01 
On some occasions, upgrading the libstdc++ is not as easy as applying a simple patch.

**Comment by tammela** [comment]
I think we can merge this, no problem.
The recommendation stills the same though. Use a stable C++17 compliant compiler / libstdc++.

**Comment by karanankit01** [comment]
OK, Fine.
It would be better if there will be recommendation message while building with lesser version.

**Comment by spacewander** [comment]
@karanankit01 
Added in the latest commit.

**Pull request merged**
